name: Linkcheck

on: [push, pull_request]

jobs:
  check_articles:
    uses: ./.github/workflows/check_articles.yml

  linkcheck:
    needs: check_articles
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"] # "3.7", , "3.9", "3.10", "3.11"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libenchant-2-dev -y
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: build documentation
        run: |
          cd docs/workshops/pioneer_line_follow
          ln -s ../../../conf.py .
          ln -s ../../../_static .
          ln -s ../../modules .
          DIR=pioneer_line_follow make html
      - name: Test external urls
        run: |
          make linkcheck
